#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - cowsay
  - lolcat
  - gcc
  - build-essential
  - cmake
  - unzip
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - openssh-server
  - zsh
  - fzf
  - ranger
  - bat
  - fd-find
  - exa
  - direnv
  - tmux
  - python3
  - python3-pip
  - ripgrep
  - libfuse2 # For bat and exa on some systems

runcmd:
  - mkdir -p /root/.config
  - curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
  - tar -C /usr/local --strip-components=1 -xzf nvim-linux64.tar.gz
  - rm nvim-linux64.tar.gz
  - ln -s /usr/local/bin/nvim /usr/bin/nvim # Ensure nvim is available globally
  - systemctl enable ssh
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce-cli
  - systemctl start ssh
  - sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  - git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  - git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  - curl -sLS https://get.arkade.dev | sh
  - arkade get kubectl helm kind
  - chsh -s $(which zsh) root
  - wget -O viddy.tar.gz https://github.com/sachaos/viddy/releases/download/v1.0.2/viddy-v1.0.2-linux-x86_64.tar.gz && tar xvf viddy.tar.gz && mv viddy /usr/local/bin
  # Install Neovim plugins (adjust command based on your plugin manager)
  - nvim --headless "+Lazy! sync" +qa
ssh_genkeytypes: ["rsa", "ecdsa", "ed25519"]
