#cloud-config
package_update: true
package_upgrade: true

# Install necessary packages
packages:
  - git
  - xclip
  - curl
  - gcc
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - openssh-server
  - zsh
  - direnv

runcmd:
  - mkdir -p /root/.config
  - curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
  - tar -C /usr/local --strip-components=1 -xzf nvim-linux64.tar.gz
  - rm nvim-linux64.tar.gz
  - ln -s /usr/local/bin/nvim /usr/bin/nvim # Ensure nvim is available globally
  - mkdir -p /root/.config/nvim # Ensure the nvim config directory exists
  - git clone https://github.com/LazyVim/starter /root/.config/nvim
  - rm -rf /root/.config/nvim/.git
  - nvim --headless "+Lazy! sync" +qa # Initialize and install plugins in headless mode
  - systemctl enable ssh
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce-cli
  - systemctl start ssh
  # Install Oh My Zsh and plugins
  - sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  - git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  - git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  # Set Zsh as the default shell
  - chsh -s $(which zsh) root
# Generate SSH key for the root user
ssh_genkeytypes: ["rsa", "ecdsa", "ed25519"]
