#cloud-config
package_update: true
package_upgrade: true
packages:
  - openssh-server
  - ufw # Firewall management
  - git

ssh_pwauth: false # Disable password authentication

runcmd:
  - sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
  - sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/' /etc/ssh/sshd_config
  - sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - ufw allow ssh
  - ufw enable
  - systemctl restart ssh
